### ISSUE TITLE
Support for Apple M1 architecture

### ISSUE THREAD

**Issue by LucaProvencal** [googleapis/google-cloud-ruby#8959] opened 2021-01-29 15:47 UTC
Hello, I am having the following issue specifically on an Apple M1 machine. Does this gem support this architecture? Perhaps the issue is not with google-cloud-pubsub, but with google/protobuf_c. Thank you

#### Environment details

  - OS: MacOS 11.0.1 (M1 chip)
  - Ruby version: 2.7.2
  - Gem name and version: google-cloud-pubsub 2.3.1

#### Steps to reproduce

  1. Install gem
  2. Try to require it

#### Code example

```ruby
require "google/cloud/pubsub"
```

#### Full backtrace

```sh
Failure/Error: require "google/cloud/pubsub"

LoadError:
  cannot load such file -- google/protobuf_c
...
# ------------------
# --- Caused by: ---
# LoadError:
#   dlopen(/Users/lucaprovencal/.rvm/gems/ruby-2.7.2/gems/google-protobuf-3.13.0-universal-darwin/lib/google/2.7/protobuf_c.bundle, 9): no suitable image found.  Did find:
#   	/Users/lucaprovencal/.rvm/gems/ruby-2.7.2/gems/google-protobuf-3.13.0-universal-darwin/lib/google/2.7/protobuf_c.bundle: mach-o, but wrong architecture
#   	/Users/lucaprovencal/.rvm/gems/ruby-2.7.2/gems/google-protobuf-3.13.0-universal-darwin/lib/google/2.7/protobuf_c.bundle: mach-o, but wrong architecture - /Users/lucaprovencal/.rvm/gems/ruby-2.7.2/gems/google-protobuf-3.13.0-universal-darwin/lib/google/2.7/protobuf_c.bundle
#   /Users/lucaprovencal/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
```

**Comment by quartzmo** [comment] 2021-01-29 17:18
@LucaProvencal Thanks for opening this issue. You are correct, the issue is with `google-protobuf`, and is generally discussed in protocolbuffers/protobuf#8062. Here's an excerpt from that discussion:

> It might take us some time to be able to start publishing precompiled binaries for Apple ARM machines, but you should still be able to use protobuf by building from source.

Regarding Ruby and `google-protobuf`, there is also a newer issue protocolbuffers/protobuf#8199 that suggests a couple of workarounds. I'm going to close this issue now, can you please comment on protocolbuffers/protobuf#8199 if the workarounds are helpful?

**Closed** 2021-01-29 17:18 UTC
Labels: api: pubsub, type: question

**Comment by LucaProvencal** [comment] 2021-02-04 18:46
@quartzmo Thanks for linking me to that issue. Yes, it solved the problem along with upgrading grpc to v1.35.0. Thanks!
