### ISSUE TITLE
Gem::MissingSpecVersionError (Gem::MissingSpecVersionError)

### ISSUE THREAD

**Issue by megha492** [googleapis/google-cloud-ruby#22895] opened 2023-09-06 11:09 UTC
I am facing the below issue after installing google-cloud-bigquery version 1.43.1
#### Environment details

  - OS:  Mac 13.5.1 
  - Ruby version: 2.6.8
  - Gem name and version: google-cloud-bigquery-1.43.1

#### Steps to reproduce

  1. ... install gem google-cloud-bigquery version 1.43.1

#### Code example

```ruby
require "google/cloud/bigquery"
```

#### Full backtrace

```sh
irb(main):001:0> require "google/cloud/bigquery"
/google/cloud/bigquery/convert.rb:16:in `<top (required)>'
rubygems/dependency.rb:316:in `to_specs'
Gem::MissingSpecVersionError (Gem::MissingSpecVersionError)
```

**Comment by SandeepTuniki** [comment] 2023-09-07 04:46
Hi @megha492, I ran the code under the same environment, but I'm not able to reproduce this error:
```sh
$ ruby --version
ruby 2.6.8p205 

$ gem list | grep google-cloud-bigquery
google-cloud-bigquery (1.43.1)

$ bundle exec irb
irb(main):001:0> require 'google/cloud/bigquery'
=> true
```

A quick Google search for the error "Gem::MissingSpecVersionError" [indicates](https://support.sequenceserver.com/t/how-do-i-solve-this-error-gem-missingspecversionerror/265/2) that this error is "Raised when trying to activate a gem, and the gem exists on the system, but not the requested version”.

Can you try to remove your Gemfile.lock and run `bundle install` again?

**Comment by SandeepTuniki** [comment] 2023-10-03 05:39
@megha492 I'm closing this issue. If the above solution doesn't work for you, feel free to re-open with by providing reproducible information.

**Closed by SandeepTuniki** 2023-10-03 05:39 UTC
Labels: type: question, api: bigquery
