### ISSUE TITLE
text to speech - cannot configure credentials using configure

### ISSUE THREAD

**Issue by scratchoo** [googleapis/google-cloud-ruby#4038] opened 2019-09-19 16:14 UTC
From the link https://googleapis.dev/ruby/google-cloud-text_to_speech/latest/file.AUTHENTICATION.html, it says that:

**The Project ID and Credentials JSON can be configured instead of placing them in environment variables or providing them as arguments.**

So  it should be possible to do:

```
Google::Cloud::TextToSpeech.configure do |config|
  config.project_id  = "my-project-id"
  config.credentials = "path/to/keyfile.json"
end
```

However an error says that configure is not method for Google::Cloud::TextToSpeech module

**Comment by dazuma** [comment] 2019-09-25 14:45
Yeah, sorry, the AUTHENTICATION file is wrong here. There isn't a config interface in that library. https://github.com/googleapis/google-cloud-ruby/issues/3494 is tracking this, so I'm going to close this as a duplicate of that one if that's okay.

**Closed by dazuma** 2019-09-25 14:45 UTC
Labels: :rotating_light:, triage me
