### ISSUE TITLE
`assertion failed` error on multi core machines with google-cloud-logging ruby gem

### ISSUE THREAD

**Issue by kumudt** [googleapis/google-cloud-ruby#1539] opened 2017-06-13 16:20 UTC
Our environment:
```
Ruby: 2.1.5
Rake: 10.4.2
Rails: 3.2.13
google-cloud gem: 0.32.0
google-cloud-logging gem: 1.1.0
grpc gem: 1.3.4
google-protobuf gem: 3.2.0.2
Docker image: ruby:2.1.5
```

We are pushing logs to Google Stackdriver from our Rails app using google-cloud-logging gem. We are using Docker to package and run our app.
When we run any rake tasks of our app (inside Docker container) on multi-core Linux machines we are getting this error.
```
E0613 15:27:13.484736145      12 sync_posix.c:47]            assertion failed: pthread_mutex_destroy(mu) == 0
rake aborted!
```
The same Docker deployment is not causing any issues on single core Linux machines or multicore OSX machines.
When we remove the stackdriver related code from our app, this error is not reproduced.
Where am I going wrong?

**Comment by hxiong388** [comment] 2017-06-13 18:16
Hi @kumudt. Thanks for reporting the issue. Unfortunately, I'm not able to replicate error you reported. I ran a dockerized Rails 3.2 app on my local multicore Linux machine and it's able to submit log entries to Stackdriver Logging service. If you're using a customized Dockerfile to build your Docker image, would you be able to provide that?

@apolcyn This error seems to be coming from [grpc gem](https://github.com/grpc/grpc/blob/cfa1035b3d5fd3ac9a44ff4e4b1b8877eb200f60/src/core/lib/support/sync_posix.c). Do you know what's causing it to happen?

**Comment by apolcyn** [comment] 2017-06-13 19:01
I can't say off the bat what would cause this. 

But +1 in order to repro, it would be great to get the docker image, and possibly a code/task to run

**Comment by kumudt** [comment] 2017-06-13 19:22
@hxiong388 @apolcyn 

My Dockerfile looks like this
```
FROM ruby:2.1.5

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN apt-get update -qq && apt-get install -y nodejs

# Install package dependencies
RUN apt-get install -y build-essential libpq-dev imagemagick cron libpng12-dev

# Installing dependent gems
RUN gem install therubyracer -v '0.12.1'
RUN gem install libv8 -v '3.16.14.7' -- --with-system-v8

# Making work directory ready for web-app
RUN mkdir /testsite
WORKDIR /testsite
ADD Gemfile /testsite/Gemfile
ADD Gemfile.lock /testsite/Gemfile.lock
ENV RUBY_VERSION=ruby-2.1.5 RAILS_ENV=staging
RUN bundle install --jobs 10 --without development test

# Copying source-code
ADD . /testsite

# Expose port
EXPOSE 3000

# Cleaning up
RUN rm -rf /var/cache/apt/archives/*.deb

# Running container script
RUN chmod +x scripts/container-script.sh
CMD ["scripts/container-script.sh"]
```
container-script.sh contains
```
(EXECJS_RUNTIME='Node' JRUBY_OPTS="-J-d32 -X-C" bundle exec rake assets:precompile) && (bundle exec rails server)
```
And it is giving me that error while executing `bundle exec rake assets:precompile`

**Comment by hxiong388** [comment] 2017-06-13 19:52
@kumudt Still no luck with the Dockerfile above (I don't have your "staging" configuration, so I tried both `RAILS_ENV=development` and `production`). My vanilla Rails 3.2 app is able to run without any errors. Are you able to to test the `google-cloud-logging` gem on a vanilla Rails 3.2 app? Also, can you be more specific on which "multi-core Linux machine" you're using?

**Comment by kumudt** [comment] 2017-06-13 20:04
@hxiong388 I am running this docker on a kubernetes 1.6.4 cluster with Ubuntu 16.04.2 LTS nodes (AWS m4.large and r4.large running kernel 4.4.0-1013-aws). It is running fine on m3.medium nodes running the same Ubuntu and kernel version.

Also, can you share this vanilla rails app? I will try to replicate the error on that app and share that with you.

**Comment by hxiong388** [comment] 2017-06-13 20:33
@kumudt It's practically a new Rails 3.2 app with nothing but `google-cloud-logging` gem and your Dockerfile. You can see it [here](https://github.com/hxiong388/rails_3_2).

**Comment by kumudt** [comment] 2017-06-13 21:57
@hxiong388 I have added our code to your Rails app and I am able to reproduce it with [this code](https://github.com/kumudt/rails_3_2.git).

**Comment by hxiong388** [comment] 2017-06-14 00:04
@kumundt I still can't get your sample app to reproduce the error. It submitted logs to Stackdriver Logging without any problem, and I didn't see anything suspicious behavior that may cause this error from reading the code.

It probably really have to do with the AWS environment that requires further diagnosis.

**Comment by kumudt** [comment] 2017-06-14 07:45
Hi @hxiong388 
You are right. This issue is specific to certain hardware. This is happening on AWS r4.large or similar instances (I have reproduced this on r4.large and i3.large).
So, I think this error is coming on all Intel Xeon E5-2686 v4 based instances.
You can reproduce this by running on r4.large or i3.large or any Intel Xeon E5-2686 v4 based instances.
```
docker run -e RAILS_ENV='staging' -p 3000:3000 kumud/rails-test:latest
```
The above image built from [this code](https://github.com/kumudt/rails_3_2/tree/na-sd)

**Comment by mterring** [comment] 2017-09-29 00:30
Hi @kumudt 
Did you get a workaround for this other than changing hardware? I'm encountering the same issue on a GKE build cluster.

**Comment by kumudt** [comment] 2017-09-29 11:28
@mterring No. I changed the machine type for that one instance group. But, haven't tested this with new grpc version.

**Comment by quartzmo** [comment] 2017-11-09 19:10
@dazuma @geigerj To whom should this issue be assigned?

**Comment by quartzmo** [comment] 2017-11-14 21:40
@dazuma @geigerj Ping. To whom should this issue be assigned? Can you suggest any steps/resolution?

**Comment by geigerj** [comment] 2017-11-15 00:16
@quartzmo Unfortunately, I don't have background on the technical details of this issue.

**Comment by quartzmo** [comment] 2017-11-15 00:31
@dazuma Can I assign this to you?

**Comment by dazuma** [comment] 2017-11-15 03:20
Yeah I'll take this. I think I've seen at least two separate reports of this, both on EC2.

**Comment by quartzmo** [comment] 2017-11-15 04:55
Thanks @dazuma!

**Comment by quartzmo** [comment] 2018-01-08 18:49
This issue is falling outside of SLO for closure. Any update?

**Comment by quartzmo** [comment] 2018-06-07 22:34
@dazuma This issue is outside of SLO. Any ideas what we can do to resolve it?

**Comment by blowmage** [comment] 2019-04-10 15:33
A lot has changed since this issue was opened. The biggest change was made in #2448, which made several changes to make Stackdriver Logging's Logger implementation thread-safe. Also, buffering and batching has also been added, so the gem's Logger and middleware can be used instead of the additional code linked to in this issue.

Because of this, I am going to close this issue as resolved. If you have issues running the latest google-cloud-logging gem in a multi-threaded environment please open a new issue.

Thanks!

**Closed by blowmage** 2019-04-10 15:33 UTC
Labels: :rotating_light:, api: logging, priority: p2, type: bug
