### ISSUE TITLE
Hanging Resque worker when using Stackdriver logging

### ISSUE THREAD

**Issue by jacobat** [googleapis/google-cloud-ruby#2459] opened 2018-09-19 13:23 UTC
Using the logging for Stackdriver in a Rails project risks running into a deadlock.

We've been looking at an issue where the Stackdriver logging caused a Resque worker process to hang. By retrieving a backtrace from the process we can see that the stackdriver logging is the cause. The backtrace showed the same `wait` and `sleep` on multiple occurrences. After removing Stackdriver the Resque worker is no longer hanging.

Here's the backtrace from the hanging process:

```
/usr/local/lib/ruby/2.4.0/monitor.rb:111:in `sleep'
/usr/local/lib/ruby/2.4.0/monitor.rb:111:in `wait'
/usr/local/lib/ruby/2.4.0/monitor.rb:111:in `wait'
/app/vendor/bundle/ruby/2.4.0/gems/google-cloud-logging-1.5.0/lib/google/cloud/logging/async_writer.rb:163:in `block in write_entries'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/app/vendor/bundle/ruby/2.4.0/gems/google-cloud-logging-1.5.0/lib/google/cloud/logging/async_writer.rb:154:in `write_entries'
/app/vendor/bundle/ruby/2.4.0/gems/google-cloud-logging-1.5.0/lib/google/cloud/logging/logger.rb:553:in `write_entry'
/app/vendor/bundle/ruby/2.4.0/gems/google-cloud-logging-1.5.0/lib/google/cloud/logging/logger.rb:317:in `add'
/app/vendor/bundle/ruby/2.4.0/gems/google-cloud-logging-1.5.0/lib/google/cloud/logging/logger.rb:195:in `debug'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/log_subscriber.rb:96:in `debug'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:95:in `debug'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:43:in `sql'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/subscriber.rb:101:in `finish'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/log_subscriber.rb:84:in `finish'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications/fanout.rb:104:in `finish'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications/fanout.rb:48:in `block in finish'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications/fanout.rb:48:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications/fanout.rb:48:in `finish'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:44:in `finish_with_state'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:29:in `instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:612:in `exec_cache'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `execute_and_clear'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:469:in `select_prepared'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:55:in `select_all'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/querying.rb:41:in `find_by_sql'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:554:in `block in exec_queries'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:578:in `skip_query_cache_if_necessary'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:542:in `exec_queries'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/association_relation.rb:34:in `exec_queries'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:414:in `load'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:200:in `records'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/finder_methods.rb:502:in `find_take'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/finder_methods.rb:103:in `take'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation/finder_methods.rb:81:in `find_by'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.0/lib/active_record/relation.rb:164:in `find_or_create_by'
...
```

**Comment by blowmage** [comment] 2018-09-19 14:31
@jacobat Thank you for the report. We will look into this.

**Comment by blowmage** [comment] 2019-04-03 23:00
Does this still happen on the latest versions of the google-cloud-logging and grpc gems?

**Comment by jacobat** [comment] 2019-04-10 11:16
I don't know as we're no longer using these gems, sorry.

**Comment by blowmage** [comment] 2019-04-10 15:22
Okay, thanks. The implementation has changed significantly from the time this issue was opened. Many issues that could have caused this were resolved. But that is only a guess as I never did reproduce this behavior. I am going to close this issue because the implementation has changed. If anyone has issues like this please open a new issue.

Thanks!

**Closed by blowmage** 2019-04-10 15:22 UTC
Labels: :rotating_light:, api: logging, triage me
