### ISSUE TITLE
Jruby compatibility

### ISSUE THREAD

**Issue by Goltergaul** [googleapis/google-cloud-ruby#5071] opened 2020-03-19 09:23 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to use the google-cloud-pubsub gem with jruby but it tries to install google-protobuf, which has c extensions

 **Describe the solution you'd like**
For it to work on jruby

**Comment by quartzmo** [comment] 2020-03-19 16:16
Closing as duplicate of #712.

**Closed by quartzmo** 2020-03-19 16:16 UTC
