### ISSUE TITLE
pubsub: add support for subscription detachment

### ISSUE THREAD

**Issue by hongalex** [googleapis/google-cloud-ruby#6484] opened 2020-06-08 22:02 UTC
We need to add support for the new subscription detachment feature, that allows users to detach subscriptions from their projects. This requires the following changes:

1. Expose the [detached bool](https://github.com/googleapis/googleapis/blob/cd804bab06e46dd1a4f16c32155fd3cddb931b52/google/pubsub/v1/pubsub.proto#L733) in the Subscription object for the client library's admin API.
2. Expose the [DetachSubscription](https://github.com/googleapis/googleapis/blob/cd804bab06e46dd1a4f16c32155fd3cddb931b52/google/pubsub/v1/pubsub.proto#L130) admin API.

**Comment by quartzmo** [comment] 2020-06-08 22:11
Duplicate of #6460. But thanks! :)

**Closed by quartzmo** 2020-06-08 22:11 UTC
Labels: api: pubsub, type: feature request
