### ISSUE TITLE
How does if_metageneration_match work with create_file?

### ISSUE THREAD

**Issue by edenman** [googleapis/google-cloud-ruby#13115] opened 2021-07-16 04:25 UTC
I'm trying to use the new `if_metageneration_match` parameter to avoid a race condition in my code's use of `create_file` (as described [here](https://cloud.google.com/storage/docs/generations-preconditions#preventing_the_race_condition)).  I currently do this:

```
        file = bucket.file file_name
        if file.nil?
          UI.success "File doesn't exist, creating it and continuing."
          bucket.create_file StringIO.new(file_contents), file_name, content_type: 'application/json'
        end
```
If this code was run twice at the same time on two different machines, they would both think they were the only one who had created the file.  I've tried switching to this:
```
        file = bucket.file file_name
        if file.nil?
          meta_version = bucket.metageneration
          UI.success "File doesn't exist, creating it and continuing. Meta version #{meta_version}"
          begin
            bucket.create_file StringIO.new(file_contents), file_name, content_type: 'application/json', if_metageneration_match: meta_version
          rescue Google::Cloud::FailedPreconditionError => e
            UI.error "Unable to write file, somebody else got there first.  Loading their file... #{e.message}"
            file = bucket.file file_name
            if file.nil?
              UI.error 'File was _still_ nil somehow?'
            end
          end
        end
```

If I run this in isolation (no other clients involved), `FailedPreconditionError` is raised.  Here's the docs on the parameter:

```@param [Integer] if_metageneration_match Makes the operation conditional on whether the file's current metageneration matches the given value.```

Ok so maybe it's not `bucket.metageneration`, since the docs say it's the _file's_ metageneration....but the file doesn't exist yet.

1) how can I get the current metageneration value for a file that does not exist?  I thought maybe it would be hardcoded as 0 or 1 but neither of those work either (I still get a `FailedPreconditionError`
2) Once I figure out ^, if I do have two clients running and one of them gets a FailedPreconditionError, how do I "refresh" the bucket and fetch the new file?  Or will `bucket.file` just work in that case? 

Sorry if any of this should be obvious, I'm a ruby n00b

#### Environment details

  - OS: Linux/Mac
  - Ruby version: 2.6.6
  - Gem name and version: google-cloud-storage (1.34.1)

**Comment by edenman** [comment] 2021-07-16 04:28
(note to self: https://github.com/googleapis/google-cloud-ruby/pull/11657 added the flag)

**Comment by edenman** [comment] 2021-08-20 02:16
@quartzmo looks like you added this flag, could you please help here?

**Comment by dazuma** [comment] 2021-08-20 04:13
quartzmo is no longer active on this particular library. I'll try to find another engineer who can help.

**Comment by bajajneha27** [comment] 2021-08-25 06:33
Thanks Eric for bringing this to us.

All cloud objects have two numbers: `generation number` and `metageneration number`. The `generation number` of an object changes if you modify the object itself and the `metageneration number` changes when the `metadata` of the object is changed. You can read more about it [here](https://cloud.google.com/storage/docs/generations-preconditions?hl=en) for better understanding.

I see that you're trying to avoid a race condition while creating the file. So, instead of using `if_metageneration_match` , you could use `if_generation_match` since the object isn't created yet. When this match precondition uses the value 0 instead of a generation number, the request only succeeds if there are no live objects in the Cloud Storage bucket with the name specified in the request [[ref](https://cloud.google.com/storage/docs/generations-preconditions?hl=en#_Preconditions)].
I'd suggest something like this:

```
        file = bucket.file file_name
        if file.nil? #If file does not exist, no generation/metageneration number
          UI.success "File doesn't exist, creating it and continuing."
          begin
            bucket.create_file StringIO.new(file_contents), file_name, content_type: 'application/json', if_generation_match: 0 #Assuming you just want to create the file and not update it.
          rescue Google::Cloud::FailedPreconditionError => e
            UI.error "Unable to write file, somebody else got there first.  Loading their file... #{e.message}"
            file = bucket.file file_name
            if file.nil?
              UI.error 'File was _still_ nil somehow?'
            end
          end
        end
```

Do, let me know if you have any other question.

**Comment by bajajneha27** [comment] 2021-08-30 11:23
I see. So, the same file gets generated twice? Does the timestamp of the file change? Can you please take a look at it and let me know?
I tried running your code in two different tabs of my terminal, it works fine. Can you please give me more details on how you're running this so that I can reproduce it?

**Comment by edenman** [comment] 2021-08-30 20:11
Hm.  It's running on Github Actions.  I'll add some more logs and try to figure out what's going on.  It's possible one of the other builds removed the lockfile and allowed both jobs to run.

**Comment by bajajneha27** [comment] 2021-08-31 07:00
Alright! Let me know if I can help.
I'm closing the issue for now, feel free to reopen it if needed.

**Closed by bajajneha27** 2021-08-31 07:00 UTC
Labels: type: question
