### ISSUE TITLE
Is Google::Cloud.datastore thread safe?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [googleapis/google-cloud-ruby#11242] opened 2021-04-28 13:26 UTC
I wonder if `Google::Cloud.datastore` is thread safe when used for read/writes like so:

```ruby
class MyModel
  attr_accessor :id

  def update(text)
    task = self.class.datastore.entity "Task", id  do |t|
      t["my_text"] = text
    end
    datastore.save task
  end

  def self.datastore
    @store ||= Google::Cloud.datastore
  end
end

# And then do the following in two different threads:

# Thread 1
m=MyModel.new
m.id = 1
m.update("what's up")

# Thread 2
m=MyModel.new
m.id = 2
m.update("hello")
```

Or should I instantiate a connection per thread to be sure no interaction happens?

```ruby
  def self.datastore
    Thread.current[:datastore] ||= Google::Cloud.datastore
  end
```

**Comment by quartzmo** [comment] 2021-04-28 23:31
@NielsKSchjoedt In fact, your question is a duplicate of #816. The answer is still that:

> it should be better to use a single client stub from a performance perspective, and there shouldn't be any reason not to use the same client as long as you have the same channel settings on all of them (e.g., all of the client stubs that you're creating use the same channel credentials, and are all set to make calls to the same server).

**Closed by quartzmo** 2021-04-28 23:31 UTC
Labels: api: datastore, type: question
