### ISSUE TITLE
Dialogflow set context in query_params gives [ResourceName error] Path 'x' does not match template 

### ISSUE THREAD

**Issue by michelson** [googleapis/google-cloud-ruby#12050] opened 2021-06-21 07:27 UTC
If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: OSX
  - Ruby version: 2.7.2
  - Gem name and version: google-cloud-dialogflow (1.3.0)

#### Steps to reproduce

  1. adds an context to query_params contexts

#### Code example

```ruby

      @project_id = config["project_id"]
      @conn = Google::Cloud::Dialogflow::sessions do |config|
        config.credentials = json_credentials
      end


      query_input = {
        text: {
          text: "hello",
          language_code: lang
        }
      }

      query_parameters = Google::Cloud::Dialogflow::V2::QueryParameters.new

      query_parameters.contexts << Google::Cloud::Dialogflow::V2::Context.new(
        name: "Lead", 
        lifespan_count: 1
      )

      request = Google::Cloud::Dialogflow::V2::DetectIntentRequest.new(
        session: "projects/#{@project_id}/agent/sessions/xxxx",
        query_input: query_input,
        query_params: query_parameters
      )


# this return the following object
# <Google::Cloud::Dialogflow::V2::DetectIntentRequest: session: "projects/f***/agent/sessions/***", query_params: <Google::Cloud::Dialogflow::V2::QueryParameters: time_zone: "", contexts: [<Google::Cloud::Dialogflow::V2::Context: name: "Lead", lifespan_count: 1>], reset_contexts: false, session_entity_types: [], webhook_headers: {}>, query_input: <Google::Cloud::Dialogflow::V2::QueryInput: text: <Google::Cloud::Dialogflow::V2::TextInput: text: "hello!", language_code: "en-US">>, input_audio: "">

      response = @conn.detect_intent request

      query_result = response.query_result
```

#### Full backtrace

```sh
irb(main):001:0> 
Caused by GRPC::InvalidArgument: 3:com.google.apps.framework.request.BadRequestException: [ResourceName error] Path 'Lead' does not match template 'projects/{project_id=*}/locations/{location_id=*}/agent/environments/{environment_id=*}/users/{user_id=*}/sessions/{session_id=*}/contexts/{context_id=*}'.. debug_error_string:{"created":"@1624259941.824194000","description":"Error received from peer ipv4:172.217.192.95:443","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"com.google.apps.framework.request.BadRequestException: [ResourceName error] Path 'Lead' does not match template 'projects/{project_id=*}/locations/{location_id=*}/agent/environments/{environment_id=*}/users/{user_id=*}/sessions/{session_id=*}/contexts/{context_id=*}'.","grpc_status":3}
from /Users/michelson/.rvm/gems/ruby-2.7.2/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status'
```
Thanks!

**Comment by quartzmo** [comment] 2021-06-30 17:17
I think the problem here is the value you are providing for `Context#name`. 

The [API docs](https://googleapis.dev/ruby/google-cloud-dialogflow/latest/Google/Cloud/Dialogflow/V2/Context.html#name-instance_method) for this field state:

> Required. The unique identifier of the context. Format: `projects/<Project ID>/agent/sessions/<Session ID>/contexts/<Context ID>`.
> The Context ID is always converted to lowercase, may only contain characters in [a-zA-Z0-9_-%] and may be at most 250 bytes long.

The resource path template shown in the error message is also a fully-qualified resource path, although (confusingly) it is different from the format shown in the docs:

```
projects/{project_id=*}/locations/{location_id=*}/agent/environments/{environment_id=*}/users/{user_id=*}/sessions/{session_id=*}/contexts/{context_id=*}
```

I'm not sure which is the correct resource path format, but try passing values for `Context#name` that match one or the other of these patterns.

**Comment by nicain** [comment] 2021-10-14 22:53
Closing this issue for now.  Feel free to reopen assign me, if the problem is still relevant.

**Closed by nicain** 2021-10-14 22:53 UTC
Labels: type: question, api: dialogflow
