### ISSUE TITLE
Dialogflow V2 always returns webhook_state unspecified for detect intent

### ISSUE THREAD

**Issue by yourivdlans** [googleapis/google-cloud-ruby#8072] opened 2020-10-29 12:14 UTC
#### Environment details

  - OS: osx
  - Ruby version: 2.6.6
  - Gem name and version: google-cloud-dialogflow-v2 (0.6.4)

#### Steps to reproduce

  1. Create an agent with webhook enabled
  1. Create an intent with webhook fulfillment enabled
  1. Execute a detect intent on the created intent
  1. Detected intent returns `WEBHOOK_STATE_UNSPECIFIED`

#### Code example

```ruby
query = { session: "your-session-id", query_input: { text: { text: "Text which matches your webhook intent" } } }
client = ::Google::Cloud::Dialogflow::V2::Sessions::Client.new { |config| config.credentials = your_credentials }
query_result = client.detect_intent(query).query_result
query_result.intent.webhook_state
```
Interestingly, when I try to fetch the intent through the intents client I do get `WEBHOOK_STATE_ENABLED` returned from `webhook_state`.

```ruby
client = ::Google::Cloud::Dialogflow::V2::Intents::Client.new { |config| config.credentials = your_credentials }
intent = client.get_intent(name: "projects/your-agent/agent/intents/your-webhook-intent")
intent.webhook_state
```

**Comment by fhinkel** [comment] 2020-12-11 15:22
Hi @yourivdlans , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Dialogflow tag](https://stackoverflow.com/questions/tagged/dialogflow-cx) is most appropriate for design and general troubleshooting.
* [Dialogsflow's public issue tracker](https://b.corp.google.com/issues?q=componentid:956347%20%2B%20status:open) is most appropriate for bugs and unexpected behavior.
* [Dialogflow Support](https://cloud.google.com/dialogflow/docs/support/getting-support)

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2020-12-11 15:22 UTC
Labels: api: dialogflow, type: question
