### ISSUE TITLE
Quickstart examples throws error: (given 1, expected 0) (ArgumentError)

### ISSUE THREAD

**Issue by TylerSustare** [googleapis/google-cloud-ruby#21691] opened 2023-05-29 03:18 UTC
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-ruby/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+ruby

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Mac OS Ventura
  - Ruby version: 3.2.1
  - Gem name and version:  `"google-cloud-firestore", "~> 0.21.1"`

#### Steps to reproduce

I'm following the quickstart example here in the docs https://firebase.google.com/docs/firestore/quickstart#ruby

Run the following code in `bin/rails console`
```
irb(main):003:0> Fuego.new
```

#### Code example
I'm using sorbet

```
# typed: strict
# frozen_string_literal: true

require "google/cloud/firestore"

class Fuego
  extend T::Sig

  sig { void }
  def initialize
    ENV["GOOGLE_APPLICATION_CREDENTIALS"] = Rails.root.join("config/credentials/gcloud-key.json").to_s

    firestore = Google::Cloud::Firestore.new(project_id: "my-project")
    collection_path = "users"

    doc_ref = firestore.doc("#{collection_path}/alovelace")

    doc_ref.set(
      {
        first: "Ada",
        last: "Lovelace",
        born: 1815,
      },
    )
  end
end
```

#### Full backtrace

```sh
irb(main):003:0> Fuego.new
/Users/tyler/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/google-gax-1.8.2/lib/google/gax/settings.rb:171:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

#### Context
It seems like this could be related to this issue https://github.com/googleapis/google-cloud-ruby/issues/8580

**Comment by JacksonRiso** [comment] 2023-07-23 23:33
FWIW, I also have this issue. 

**Environment details**

OS: Mac OS Ventura 13.4.1 
Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]
Gem name and version: "google-cloud-firestore", "~> 0.21.1"

**Steps to reproduce**
Follow the quickstart. For me, it's 
    
```ruby
require "google/cloud/firestore"
    params ||= {id: "1TDi3O4ZIzNAFQcMTSkb"}
    firestore = Google::Cloud::Firestore.new
    doc_ref  = firestore.doc("messages/#{params[:id]}")
    doc = doc_ref.get
``` 
    
Error: 
`/gems/ruby-3.2.2/gems/google-gax-1.8.2/lib/google/gax/settings.rb:171:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)`

**Comment by JacksonRiso** [comment] 2023-07-23 23:37
@TylerSustare I figured it out. Remove "~> 0.21.1" from gemfile, run bundle update. Latest firestore version is 2.13.1. It now works for me.

**Comment by meredithslota** [comment] 2023-10-10 00:55
@JacksonRiso Thank you for finding this! Can you point me to where you are seeing this "~> 0.21.1" in a quickstart? I can't see anything referenced in https://firebase.google.com/docs/firestore/quickstart#ruby

**Comment by JacksonRiso** [comment] 2023-10-10 02:58
Hey @meredithslota! Thanks for following up on this. 

I am not seeing it either, nor in the wayback machine. I would love to think that both @TylerSustare and I didn't just hallucinate this together, but I can't seem to find where we picked up 0.21.1 from. @TylerSustare Do you remember?

**Comment by NivedhaSenthil** [comment] 2023-10-27 06:01
Closing this for now as the actual issue is fixed, please feel free to reopen if the reference is found.

**Closed by NivedhaSenthil** 2023-10-27 06:01 UTC
Labels: type: bug, priority: p2
