### ISSUE TITLE
How to easily impersonate a service account?

### ISSUE THREAD

**Issue by stiak** [googleapis/google-cloud-ruby#17915] opened 2022-03-25 06:34 UTC
**Is your feature request related to a problem? Please describe.**
Is there an easier way to impersonate a service account than this?

```ruby
ENV[ENV_GCP_SERVICE_ACCOUNT] = "my-service-account@my-project.iam.gserviceaccount.com"
ENV[ENV_GCP_PROJECT_ID] = 'my-project'

creds_service = Google::Apis::IamcredentialsV1::IAMCredentialsService.new
creds_service.authorization = Google::Auth.get_application_default
account_name = ENV[ENV_GCP_SERVICE_ACCOUNT]
request = Google::Apis::IamcredentialsV1::GenerateAccessTokenRequest.new(
  lifetime: "3600s",
  scope: ["https://www.googleapis.com/auth/cloud-platform"]
)
impersonated_account = creds_service.generate_service_account_access_token("projects/-/serviceAccounts/#{account_name}", request)
client = Signet::OAuth2::Client.new
client.access_token = impersonated_account.access_token

Google::Cloud::Storage.new(credentials: client, project_id: ENV[ENV_GCP_PROJECT_ID])
```

 **Describe the solution you'd like**
This seems like a long way around to impersonate another service account.  Ideally I'd be able to specify the service account as part of the client constructor.  e.g.
```ruby 
Google::Cloud::Storage.new(impersonate_service_account: ENV[ENV_GCP_SERVICE_ACCOUNT], project_id: ENV[ENV_GCP_PROJECT_ID])
```

It would then obtain default credentials (like it already does) then use them to impersonate the service account provided.

 **Describe alternatives you've considered**
The example I gave works for now, it'd just be nice if it was encapsulated in the client library rather than my own code.  In order to avoid long lived access tokens, I'm going to have to implement this code multiple times.

**Comment by NivedhaSenthil** [comment] 2022-05-26 11:49
There is no straight forward way as of now to impersonate a service account. Please add your thought here https://github.com/googleapis/google-auth-library-ruby/issues/353 which tries to address the same. Closing this as its a duplicate of above mentioned issue.

**Closed by NivedhaSenthil** 2022-05-26 11:49 UTC
Labels: triage me, :rotating_light:
